### ISSUE TITLE
Testing related questions

### ISSUE THREAD

**Issue by imGurpreetSK** [codeOfRobin/Questions-to-ask-your-interviewer-iOS#1]
1. Do you write tests? If yes, what types (Unit / Integration / Functional / UI)?
2. Does management feel writing tests is 'not an important thing' / 'can be taken up later'?
3. How does QA team operate? Do they have a automated test suite or do the do manual testing for all features/regressions?
(4. Views on TDD?)

**Comment by imGurpreetSK** [comment]
Please see #2

**Comment by codeOfRobin** [comment]
Resolved from #2
